In [ ]:
import torch

#Initialzing Tensor

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [ ]:
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype = torch.float32, requires_grad = True)
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)

In [ ]:
my_tensor.dtype

torch.float32

In [ ]:
my_tensor.device

device(type='cpu')

In [ ]:
my_tensor.shape

torch.Size([2, 3])

In [ ]:
my_tensor.requires_grad

True

In [ ]:
x = torch.empty(size = (3,3)) ## Tensor of shape 3x3 with uninitialized data
x

tensor([[-4.3769e-01,  3.0635e-41,  3.3631e-44],
        [ 0.0000e+00,         nan,  6.0000e+00],
        [ 1.1578e+27,  1.1362e+30,  7.1547e+22]])

In [ ]:
x = torch.zeros(size = (3,3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
x = torch.rand((3,3)) # Tensor of shape 3x3 with values from uniform distribution in interval [0,1)
x

tensor([[0.9322, 0.7877, 0.7887],
        [0.9681, 0.5157, 0.9199],
        [0.7193, 0.0525, 0.1719]])

In [ ]:
x = torch.ones((3,3)) # Tensor of shape 3x3 with values of 1
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
x = torch.eye(5) #identity matrix
x

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
x = torch.arange(start = 0, end = 5, step = 1)
x, x.shape

(tensor([0, 1, 2, 3, 4]), torch.Size([5]))

In [ ]:
x = torch.linspace(start = 0.1, end = 1, steps = 8)
x, x.shape

(tensor([0.1000, 0.2286, 0.3571, 0.4857, 0.6143, 0.7429, 0.8714, 1.0000]),
 torch.Size([8]))

In [ ]:
x = torch.empty((1, 5)).normal_(mean = 0, std = 1) # Normally distributed with mean=0, std=1
x

tensor([[-0.5658, -0.8268,  0.1886, -1.2738, -0.9480]])

In [ ]:
x = torch.empty((1, 5)).uniform_(0, 1) # Values from a uniform distribution low=0, high=1
x

tensor([[0.1073, 0.2993, 0.2807, 0.9832, 0.1425]])

In [ ]:
x = torch.diag(torch.ones(4)) # Diagonal matrix of shape 4x4
x

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

##How to make initialized tensors to other types (int, float, double)

In [ ]:
tensor = torch.arange(0, 4) #Initialized as int64 by default
tensor, tensor.dtype

(tensor([0, 1, 2, 3]), torch.int64)

In [ ]:
tensor.bool() # Converted to Boolean: 1 if nonzero

tensor([False,  True,  True,  True])

In [ ]:
tensor.short().dtype # Converted to int16

torch.int16

In [ ]:
tensor.long().dtype # Converted to int64

torch.int64

In [ ]:
tensor.half() # Converted to float16

tensor([0., 1., 2., 3.], dtype=torch.float16)

In [ ]:
tensor.float() # Converted to float32

tensor([0., 1., 2., 3.])

In [ ]:
tensor.double() # Converted to float64

tensor([0., 1., 2., 3.], dtype=torch.float64)

##Array to Tensor conversion and vice-versa

In [ ]:
import numpy as np

In [ ]:
np_array = np.zeros((5, 5))
np_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
tensor = torch.from_numpy(np_array)
tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)

In [ ]:
np_array_back = tensor.numpy()
np_array_back

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#Tensor Math & Comparison Operations 

In [ ]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])

Addition

In [ ]:
z1 = torch.empty(3)
torch.add(x, y, out = z1)
z1

tensor([10., 10., 10.])

In [ ]:
z2 = torch.add(x, y) #This is another way
z2

tensor([10, 10, 10])

In [ ]:
z = x + y #This is other way
z

tensor([10, 10, 10])

Subtraction

In [ ]:
z = x - y
z

tensor([-8, -6, -4])

Division

In [ ]:
z = torch.true_divide(x, y)
z

tensor([0.1111, 0.2500, 0.4286])

Inplace Operations

In [ ]:
t = torch.zeros(3)
t.add_(x)
t

tensor([1., 2., 3.])

In [ ]:
t += x
t

tensor([2., 4., 6.])

Exponentiation

In [ ]:
z = x.pow(2)
z

tensor([1, 4, 9])

In [ ]:
z = x**2
z

tensor([1, 4, 9])

Simple comparisons

In [ ]:
z = x > 0
z

tensor([True, True, True])

In [ ]:
z = x < 0
z

tensor([False, False, False])

Matrix Multiplication

In [ ]:
x1 = torch.rand((2, 5))
x2 = torch.rand((5, 3))
x3 = torch.mm(x1, x2)
x3

tensor([[0.5563, 0.8440, 0.7745],
        [0.7161, 1.4716, 1.1797]])

In [ ]:
x3 = x1.mm(x2) #another way
x3

tensor([[0.5563, 0.8440, 0.7745],
        [0.7161, 1.4716, 1.1797]])

Matrix exponentiation

In [ ]:
matrix_exp = torch.rand(5, 5)
matrix_exp.matrix_power(3)  # is same as matrix_exp (mm) matrix_exp (mm) matrix_exp

tensor([[5.6555, 5.1765, 5.5796, 3.3175, 2.2432],
        [4.5018, 4.3208, 4.2859, 2.7565, 1.8566],
        [4.0883, 3.5758, 4.1948, 2.3545, 1.6200],
        [4.6346, 4.2273, 4.4698, 2.7379, 1.8855],
        [3.9992, 3.5388, 3.7918, 2.2384, 1.5355]])

Element wise multiplication

In [ ]:
z = x * y
z

tensor([ 9, 16, 21])

Dot product

In [ ]:
z = torch.dot(x, y)
z

tensor(46)

Batch Matrix Multiplication

In [ ]:
batch = 32
n = 10
m = 20
p = 30

In [ ]:
tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
out_bmm = torch.bmm(tensor1, tensor2) # Will be shape: (b x n x p)
out_bmm[2]

tensor([[4.6363, 6.5409, 5.3746, 4.4489, 5.2535, 6.5553, 5.4093, 6.1074, 3.7201,
         5.1652, 5.0154, 5.7328, 5.0090, 4.4519, 6.0133, 4.4113, 5.2161, 4.1146,
         4.3802, 4.0611, 4.1409, 5.8487, 4.7867, 5.0938, 4.5757, 5.5300, 4.0907,
         5.1513, 5.6065, 3.3424],
        [3.3269, 4.3795, 4.1767, 3.4888, 4.4400, 4.6329, 3.8056, 4.5658, 3.6289,
         4.2806, 3.9482, 4.3558, 3.8429, 3.0261, 4.2062, 3.0417, 3.3361, 3.5631,
         4.5263, 3.0650, 3.0298, 4.1446, 3.8792, 3.7738, 3.4724, 4.3133, 3.8931,
         4.0541, 4.3429, 2.5627],
        [4.1342, 4.7938, 3.6371, 3.4015, 4.0770, 5.0879, 4.0134, 4.4803, 3.3343,
         4.3313, 4.6180, 4.9645, 5.0563, 4.0392, 4.6211, 4.1494, 4.3953, 3.9992,
         3.9316, 3.7252, 3.0451, 4.6174, 3.3274, 3.7305, 4.6979, 3.6244, 4.1606,
         3.9689, 5.0699, 2.9752],
        [5.1481, 5.8446, 4.1476, 4.4335, 5.8985, 6.2001, 5.3510, 5.2018, 3.8714,
         5.0066, 5.0450, 5.6708, 5.4126, 5.4542, 5.2107, 4.1152, 5.8159, 5.6284,
       

Broadcasting

In [ ]:
x1 = torch.rand((5, 5))
x2 = torch.ones((1, 5))
x1, x2

(tensor([[0.3994, 0.7818, 0.3163, 0.3021, 0.2751],
         [0.2010, 0.8881, 0.1199, 0.1108, 0.2732],
         [0.7326, 0.8354, 0.9611, 0.8567, 0.4453],
         [0.7711, 0.3719, 0.3144, 0.4606, 0.2151],
         [0.1218, 0.4925, 0.2430, 0.9652, 0.3509]]),
 tensor([[1., 1., 1., 1., 1.]]))

In [ ]:
z = x1 - x2
z

tensor([[-0.6006, -0.2182, -0.6837, -0.6979, -0.7249],
        [-0.7990, -0.1119, -0.8801, -0.8892, -0.7268],
        [-0.2674, -0.1646, -0.0389, -0.1433, -0.5547],
        [-0.2289, -0.6281, -0.6856, -0.5394, -0.7849],
        [-0.8782, -0.5075, -0.7570, -0.0348, -0.6491]])

In [ ]:
z = x1 * x2
z

tensor([[0.3994, 0.7818, 0.3163, 0.3021, 0.2751],
        [0.2010, 0.8881, 0.1199, 0.1108, 0.2732],
        [0.7326, 0.8354, 0.9611, 0.8567, 0.4453],
        [0.7711, 0.3719, 0.3144, 0.4606, 0.2151],
        [0.1218, 0.4925, 0.2430, 0.9652, 0.3509]])

In [ ]:
z = x1 ** x2
z

tensor([[0.3994, 0.7818, 0.3163, 0.3021, 0.2751],
        [0.2010, 0.8881, 0.1199, 0.1108, 0.2732],
        [0.7326, 0.8354, 0.9611, 0.8567, 0.4453],
        [0.7711, 0.3719, 0.3144, 0.4606, 0.2151],
        [0.1218, 0.4925, 0.2430, 0.9652, 0.3509]])

Other useful tensor operations

In [ ]:
x

tensor([1, 2, 3])

In [ ]:
sum_x = torch.sum(x, dim = 0)  # Sum of x across dim=0
sum_x

tensor(6)

In [ ]:
values, indices = torch.max(x, dim = 0) # Can also do x.max(dim=0)
values, indices

(tensor(3), tensor(2))

In [ ]:
values, indices = torch.min(x, dim = 0) # Can also do x.min(dim=0)
values, indices

(tensor(1), tensor(0))

In [ ]:
abs = torch.abs(x) #Returns x where abs function has been applied to every element
abs

tensor([1, 2, 3])

In [ ]:
z = torch.argmax(x, dim = 0) # Gets index of the maximum value
z

tensor(2)

In [ ]:
z = torch.argmin(x, dim=0)  # Gets index of the minimum value
z

tensor(0)

In [ ]:
mean_x = torch.mean(x.float(), dim = 0) # mean requires x to be float
mean_x

tensor(2.)

In [ ]:
z = torch.eq(x, y) # Element wise comparison, in this case z = [False, False, False]
z

tensor([False, False, False])

In [ ]:
sorted_y, indices = torch.sort(y, dim = 0, descending = False)
sorted_y, indices

(tensor([7, 8, 9]), tensor([2, 1, 0]))

In [ ]:
z = torch.clamp(x, min = 0) # All values < 0 set to 0 and values > 0 unchanged (this is exactly ReLU function)
z

tensor([1, 2, 3])

In [ ]:
z = torch.clamp(x, min=1, max=2) # If you want to values over max_val to be clamped
z

tensor([1, 2, 2])

In [ ]:
x = torch.tensor([1, 0, 1, 4, 1], dtype=torch.bool)  # True/False values
x

tensor([ True, False,  True,  True,  True])

In [ ]:
z = torch.any(x)  # will return True, can also do x.any() instead of torch.any(x)
z

tensor(True)

In [ ]:
z = torch.all(x)  # will return False (since not all are True), can also do x.all() instead of torch.all()
z

tensor(False)

#Tensor Indexing

In [ ]:
batch_size = 10
features = 25
x = torch.rand((batch_size, features))
x

tensor([[6.3704e-01, 7.3997e-01, 9.1058e-01, 8.6653e-01, 8.9784e-02, 2.7031e-01,
         8.6583e-01, 6.3982e-01, 5.0306e-01, 9.5555e-01, 9.7034e-01, 5.5698e-02,
         8.7962e-01, 1.5362e-01, 7.8777e-02, 5.9685e-01, 2.7512e-01, 7.7798e-01,
         8.8096e-02, 1.2160e-01, 7.7259e-01, 3.8611e-01, 5.5627e-01, 9.6331e-01,
         5.0210e-01],
        [9.7316e-01, 9.5794e-01, 5.6975e-01, 2.0415e-01, 3.2830e-01, 4.8152e-01,
         1.3743e-02, 1.5199e-01, 3.4877e-01, 6.3473e-02, 3.8945e-01, 5.1652e-02,
         5.5930e-01, 7.4691e-01, 5.3945e-01, 7.7237e-01, 3.6313e-01, 5.8997e-01,
         9.9456e-01, 8.8201e-01, 2.7981e-01, 7.4730e-01, 2.5536e-01, 4.6646e-01,
         5.5428e-02],
        [7.3213e-01, 1.7055e-02, 3.9112e-01, 3.6385e-01, 7.6769e-01, 7.2931e-01,
         1.7355e-01, 2.5236e-01, 8.9368e-01, 2.6101e-01, 4.7262e-01, 6.0257e-01,
         1.3428e-01, 7.2967e-01, 4.2532e-01, 7.3457e-01, 8.4768e-01, 4.6952e-01,
         7.8739e-01, 4.5845e-01, 8.1966e-01, 3.7307e-01, 6.6268e-

In [ ]:
x.shape

torch.Size([10, 25])

In [ ]:
# Get first examples features
print(x[0].shape)  # shape [25], this is same as doing x[0,:]

torch.Size([25])


In [ ]:
x[0,:]

tensor([0.6370, 0.7400, 0.9106, 0.8665, 0.0898, 0.2703, 0.8658, 0.6398, 0.5031,
        0.9556, 0.9703, 0.0557, 0.8796, 0.1536, 0.0788, 0.5969, 0.2751, 0.7780,
        0.0881, 0.1216, 0.7726, 0.3861, 0.5563, 0.9633, 0.5021])

In [ ]:
x[2, 0:10]

tensor([0.7321, 0.0171, 0.3911, 0.3638, 0.7677, 0.7293, 0.1736, 0.2524, 0.8937,
        0.2610])

In [ ]:
x[0, 0] = 100

Fancy indexing

In [ ]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
indices = [2, 5, 8]
x[indices]

tensor([2, 5, 8])

In [ ]:
x = torch.rand((3, 5))
x

tensor([[0.2521, 0.4008, 0.1772, 0.0645, 0.2778],
        [0.8547, 0.7958, 0.6292, 0.9598, 0.4604],
        [0.9105, 0.5266, 0.5074, 0.4271, 0.3535]])

In [ ]:
rows = torch.tensor([1, 0])
cols = torch.tensor([4, 0])
x[rows, cols]

tensor([0.4604, 0.2521])

More advanced indexing

In [ ]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[(x < 2) | (x > 8)] 

tensor([0, 1, 9])

In [ ]:
x[x.remainder(2) == 0]

tensor([0, 2, 4, 6, 8])

In [ ]:
x.remainder(3) == 0

tensor([ True, False, False,  True, False, False,  True, False, False,  True])

Useful operations

In [ ]:
torch.where(x > 5, x, x * 2)
#x > 5 return x else return x*2

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])

In [ ]:
x = torch.tensor([0, 0, 1, 2, 2, 3, 4]).unique()
x

tensor([0, 1, 2, 3, 4])

In [ ]:
x.ndimension() # number of dimensions

1

In [ ]:
x.numel() # number of elements

5

#Tensor Reshaping

In [ ]:
x = torch.arange(9)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# Let's say we want to reshape it to be 3x3
x_3x3 = x.view(3, 3)
x_3x3

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [ ]:
x_3x3 = x.reshape(3, 3)
x_3x3

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [ ]:
y = x_3x3.t()
y

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

In [ ]:
y.is_contiguous()

False

In [ ]:
x1 = torch.rand(2, 5)
x2 = torch.rand(2, 5)
x1, x2

(tensor([[0.4807, 0.7088, 0.8628, 0.9527, 0.1524],
         [0.2925, 0.0113, 0.6151, 0.2382, 0.5104]]),
 tensor([[0.5938, 0.7584, 0.1264, 0.5488, 0.2947],
         [0.9553, 0.9199, 0.2940, 0.6846, 0.3569]]))

In [ ]:
z1 = torch.cat((x1, x2), dim = 0) #shape: 4x5
z1.shape

torch.Size([4, 5])

In [ ]:
z2 = torch.cat((x1, x2), dim = 1) #shape: 2x10
z2.shape

torch.Size([2, 10])

In [ ]:
# Let's say we want to unroll x1 into one long vector with 10 elements, we can do:
z = x1.reshape(-1)
z

tensor([0.4807, 0.7088, 0.8628, 0.9527, 0.1524, 0.2925, 0.0113, 0.6151, 0.2382,
        0.5104])

In [ ]:
batch = 64
x = torch.rand((batch, 2, 5))
z = x.reshape(batch, -1)
z.shape

torch.Size([64, 10])

In [ ]:
# Let's say we want to switch x axis so that instead of 64x2x5 we have 64x5x2
z = x.permute(0, 2, 1)
z.shape

torch.Size([64, 5, 2])

In [ ]:
x = torch.arange(10)
x, x.shape

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([10]))

In [ ]:
z = x.unsqueeze(0)
z, z.shape

(tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 10]))

In [ ]:
z = x.unsqueeze(1)
z, z.shape

(tensor([[0],
         [1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]), torch.Size([10, 1]))

In [ ]:
z = x.unsqueeze(0).unsqueeze(1)
z, z.shape

(tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]]), torch.Size([1, 1, 10]))

In [ ]:
y = z.squeeze(1)
y, y.shape

(tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 10]))

In [ ]:
x = torch.rand((batch, 2, 5))
x.shape

torch.Size([64, 2, 5])

In [ ]:
# Splits x last dimension into chunks of 2 (since 5 is not integer div by 2) the last dimension
# will be smaller, so it will split it into two tensors: 64x2x3 and 64x2x2
z = torch.chunk(x, chunks=2, dim=1)
z[0].shape, z[1].shape

(torch.Size([64, 1, 5]), torch.Size([64, 1, 5]))